---

# This is a default vars file based off of the behavior of the original installer script.

# Set this variable to the path of your local agent-install.cfg
# It will be copied onto the remote system, and then loaded into the Ansible SSH session env.
agent_install: null

# Set this variable to the path 
administrator_env: null

# If true, exports this config with populated secrets using the imported vault secret.
export_data: false

# If true, uninstalls the management hub.
# This is a destructive operation.
uninstall: false

# If true, installs the management hub.
install: false

# If true, upgrades the management hub.
upgrade: false

# This is an additional place to define the configuration for the management hub.
# If fields are not given, then the playbook will generate defaults.
# For now, that is handled by the deploy-mgmt-hub script.
hzn_mgmt_hub:
  config: {}

  fdo:
    config: {}
    secrets: {}
    net: {}

  agent:
    config: {}

  vault:
    config: {}
    secrets: {}
    net: {}

  mongo: 
    config: {}
    secrets: {}
    net: {}

  postgres:
    config: {}
    secrets: {}
    net: {}

  css:
    config: {}
    secrets: {}
    net: {}

  exchange:
    # General settings for the exchange container.
    config: {}

    # Secrets for the exchange container. When set to null, they will be generated.
    # These keys can not be generated by Ansible.
    # Either set them to known values, or do not provide them.
    # root_pw: null
    # root_pw_bcrypted: null
    secrets: {}

    # Network settings for the exchange container.
    net: {}

  hzn:
    config: {}
    secrets: {}
    net: {}
  agbot:
    config: {}
    secrets: {}
    net:  {}

  agbot2: {}
  oh:
    config: {}
